"use client";

import { Search, SlidersHorizontal, X } from "lucide-react";
import type { Difficulty, GameCategory } from "./GameCard";

type GameFiltersProps = { search: string; category: GameCategory | "All Games"; difficulty: Difficulty | "All"; onSearchChange: (value: string) => void; onCategoryChange: (value: GameCategory | "All Games") => void; onDifficultyChange: (value: Difficulty | "All") => void };
const categories: Array<GameCategory | "All Games"> = ["All Games", "Quick Games", "Puzzle", "Arcade", "Quiz"];
const difficulties: Array<Difficulty | "All"> = ["All", "Easy", "Medium", "Hard"];

export default function GameFilters({ search, category, difficulty, onSearchChange, onCategoryChange, onDifficultyChange }: GameFiltersProps) { return <div className="glass rounded-2xl p-3"><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[#777482]" size={17} /><input value={search} onChange={(event) => onSearchChange(event.target.value)} placeholder="Search games..." aria-label="Search games" className="h-12 w-full rounded-xl border border-white/[.07] bg-white/[.035] pl-11 pr-11 text-sm text-white outline-none placeholder:text-[#777482] focus:border-[#ff4058]/60" />{search && <button aria-label="Clear search" onClick={() => onSearchChange("")} className="absolute right-3 top-1/2 -translate-y-1/2 p-2 text-[#777482] hover:text-white"><X size={15} /></button>}</div><div className="mt-4 flex flex-col gap-3 border-t border-white/[.07] pt-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{categories.map((item) => <button key={item} onClick={() => onCategoryChange(item)} className={`rounded-lg px-3 py-2 text-xs font-bold transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#ff4058] ${category === item ? "bg-[#ff4058] text-white" : "bg-white/[.04] text-[#85818e] hover:bg-white/[.09] hover:text-white"}`}>{item}</button>)}</div><div className="flex items-center gap-2"><SlidersHorizontal size={15} className="text-[#777482]" /><span className="mr-1 text-[10px] uppercase tracking-[.12em] text-[#777482]">Difficulty</span>{difficulties.map((item) => <button key={item} onClick={() => onDifficultyChange(item)} className={`rounded-md px-2.5 py-1.5 text-[11px] font-bold transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#ff4058] ${difficulty === item ? "bg-white text-[#100e13]" : "text-[#85818e] hover:text-white"}`}>{item}</button>)}</div></div></div>; }