"use client";

import { Brain, Clock3, Gamepad2, Home, Target, Trophy } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import GameCard, { type Difficulty, type Game, type GameCategory } from "./GameCard";
import GameFilters from "./GameFilters";

const games: Game[] = [{ id: "tic-tac-toe", title: "Tic Tac Toe", category: "Quick Games", difficulty: "Easy", players: 2, xpReward: 100, description: "Outsmart your opponent and claim the board in this timeless strategy classic.", aiBadge: "AI Available", Icon: Target }, { id: "memory-match", title: "Memory Match", category: "Puzzle", difficulty: "Medium", players: 1, xpReward: 150, description: "Test your memory, match every pair, and sharpen your focus under pressure.", aiBadge: "AI Challenge", Icon: Brain }, { id: "reaction-rush", title: "Reaction Rush", category: "Arcade", difficulty: "Medium", players: 1, xpReward: 120, description: "Fast hands win here. React quickly, stay sharp, and chase a new high score.", aiBadge: "AI Benchmark", Icon: Clock3 }, { id: "quick-quiz", title: "Quick Quiz", category: "Quiz", difficulty: "Easy", players: 1, xpReward: 100, description: "Put your knowledge to the test with rapid-fire questions across every topic.", aiBadge: "AI Battle", Icon: Trophy }];

export default function GameLobby() { const [search, setSearch] = useState(""); const [category, setCategory] = useState<GameCategory | "All Games">("All Games"); const [difficulty, setDifficulty] = useState<Difficulty | "All">("All"); const filteredGames = useMemo(() => games.filter((game) => { const searchMatch = `${game.title} ${game.description} ${game.category}`.toLowerCase().includes(search.toLowerCase()); return searchMatch && (category === "All Games" || game.category === category) && (difficulty === "All" || game.difficulty === difficulty); }), [category, difficulty, search]); return <main className="min-h-screen bg-[#08080b] pb-24 pt-24"><div className="container-wide"><div className="mb-12 flex flex-col justify-between gap-6 border-b border-white/[.07] pb-10 md:flex-row md:items-end"><div><Link href="/" className="mb-7 inline-flex items-center gap-2 text-xs font-bold text-[#85818e] transition hover:text-white"><Home size={14} /> Back home</Link><div className="eyebrow mb-4">The NEXPLAY arena</div><h1 className="text-[clamp(42px,7vw,72px)] font-black leading-[.9] tracking-[-.06em]">GAME <span className="text-[#ff4058]">LOBBY</span></h1><p className="section-copy mt-5 max-w-[480px] text-sm">Choose a game, sharpen your skills, and earn XP.</p></div><div className="flex items-center gap-3 text-xs text-[#85818e]"><span className="h-2 w-2 rounded-full bg-[#60dba2]" /> 4 games available</div></div><GameFilters search={search} category={category} difficulty={difficulty} onSearchChange={setSearch} onCategoryChange={setCategory} onDifficultyChange={setDifficulty} /><div className="mt-10 flex items-center justify-between"><p className="text-xs text-[#85818e]">Showing <strong className="text-white">{filteredGames.length}</strong> of {games.length} games</p><Gamepad2 size={18} className="text-[#ff4058]" /></div>{filteredGames.length > 0 ? <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{filteredGames.map((game, index) => <GameCard key={game.id} game={game} index={index} />)}</div> : <div className="glass mt-5 rounded-2xl py-20 text-center"><Gamepad2 className="mx-auto mb-4 text-[#ff4058]" size={32} /><h2 className="text-lg font-bold text-white">No games found</h2><p className="mt-2 text-sm text-[#85818e]">Try another search or reset your filters.</p><button onClick={() => { setSearch(""); setCategory("All Games"); setDifficulty("All"); }} className="ghost-button mt-6">Reset filters</button></div>}</div></main>; }